baseURL = "https://archana.buzz/"
languageCode = "en-us"
title = "Archana's Blog - Welcome to my Blog"
theme = "parsa-hugo"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "Homepage"
url = ""
weight = 1
hasChildren = true

  [[menu.main]]
  parent = "Homepage"
  name = "Homepage 1"
  url = "homepage/home-1"

  [[menu.main]]
  parent = "Homepage"
  name = "Homepage 2"
  url = "homepage/home-2"

[[menu.main]]
name = "About"
url = "about"
weight = 2

[[menu.main]]
name = "Contact"
url = "contact"
weight = 3

[params]
logo = "images/logo.png"
home = "Home"
layout = "1"
description = "My random musings on Life & Tech"
preloader = true
search = true
author = "Archana S"
author_image = "images/banner-img.png"
bio = "Archana is a Technical Consultant, Baker and a fun loving person. Learn more about her as you read through this blog."
mobile = ""
email = "archana.sunil97@gmail.com"
address = "Bengaluru"
contact_form_action = "#"
copyright = "Copyright &copy; 2021 Archana S. A theme by [themefisher.com](themefisher.com)"